### ISSUE TITLE
Many ZoneMinder browser windows don't scale to content correctly

### ISSUE THREAD

**Issue by davenz** [ZoneMinder/ZoneMinder#1059]
These are seemingly minor usability issues which cumulatively end up consuming quite a bit of time. The client system is running Ubuntu 14.04, Firefox v40, all at 100 percent zoom. Server is ZoneMinder v1.28.1, installed from PPA. The "flat" skin is enabled.

For example, the window to enable/disable a monitor (note the scroll bars because it's not scaling to content correctly):
![zoneminder-issues 1](https://cloud.githubusercontent.com/assets/3925818/9975391/2a3e3ce2-5f0f-11e5-94f2-43c03ec9b75d.png)

The same for monitor settings:
![zoneminder-issues 5](https://cloud.githubusercontent.com/assets/3925818/9975409/92e9cb9e-5f0f-11e5-8793-e1c09ccb775c.png)

And when opening a window to define zones:
![zoneminder-issues 2](https://cloud.githubusercontent.com/assets/3925818/9975401/6bb9cb5a-5f0f-11e5-97ae-eb24cca013f5.png)

Here is the same above window but maximized. This is the view I want to see initially, without having to manually scroll and maximize:

![zoneminder-issues 3](https://cloud.githubusercontent.com/assets/3925818/9975405/846169b0-5f0f-11e5-968a-c01e64e2aa3a.png)
##

**Comment by connortechnology** [comment]
Lots of these are fixed in master.

**Comment by alager** [comment]
Configuring monitors is still not sized correctly in 1.28.107
![monitor_config](https://cloud.githubusercontent.com/assets/14002638/10257486/952f070a-690c-11e5-91bf-e48f2f7c2734.png)
