### ISSUE TITLE
Tar error: Cowardly refusing to create empty archive!

### ISSUE THREAD

**Issue by zaheer308** [ZoneMinder/zoneminder#2239]
The problem is on zoneminder 1.32.1 running on Ubuntu  18.04

**Relevant log lines:**
```
`

2
2018-10-08 14:20:01 | zmfilter_3 |   | 1035 | ERR | Tar error: Cowardly refusing to create empty archive! | zmfilter.pl |  
2018-10-08 14:20:01 | zmfilter_3 |   | 1035 | INF | Archiving event 10 | zmfilter.pl |  
2018-10-08 14:20:01 | zmfilter_3 |   | 1035 | INF | Creating upload file '/tmp/zm/ipcam-10.tar', 0 files | zmfilter.pl |  
2018-10-08 14:20:01 | zmfilter_3 |   | 1035 | ERR | Tar error: Cowardly refusing to create empty archive! | zmfilter.pl |  
2018-10-08 14:20:01 | zmfilter_3 |   | 1035 | INF | Archiving event 11 | zmfilter.pl |  
2018-10-08 14:20:01 | zmfilter_3 |   | 1035 | INF | Creating upload file '/tmp/zm/ipcam-11.tar', 0 files | zmfilter.pl

`

log lines here
```

**Comment by knight-of-ni** [comment]
The assumption here is that you are recording to mp4 only, not jpg.

Fixed in commit 428b2506ec033d0e1ae499f71ed0db9db631df10

**Comment by zaheer308** [comment]
@knight-of-ni  still getting same error after changing zmfilter.pl
