### ISSUE TITLE
mpeg stream instead of jpeg is crashing (seg fault) on 1.26.4 [$10]

### ISSUE THREAD

**Issue by lpallard1** [ZoneMinder/ZoneMinder#247]
Upon switching the stream playback to mpeg instead of jpeg, zoneminder appears to hard crash and the monitors status becomes red.

The logs are showing:

getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
Monitor-1: 4161000 - Capturing at 14.93 fps
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
Monitor-1: 4156000 - Processing at 14.93 fps
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
getStreamCmdResponse stream error: socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused - checkStreamForErrors()
socket_sendto( /var/run/zm/zms-345613s.sock ) failed: Connection refused
Signal address is 0xa0, from 0x7f7c0c350af7
Got signal 11 (Segmentation fault), crashing
Signal address is 0xa0, from 0x7fab20d48af7
Got signal 11 (Segmentation fault), crashing

Switching back to jpeg and restarting causes zoneminder to work OK.  what I find strange is the presence of messages such as "Processing at XXfps" and "Capturing at XXfps" which IMO indicates that not all has crashed...
##

**Comment by connortechnology** [comment]
Can you test current master branch to see if I have fixed this crash?

**Comment by kk7ds** [comment]
As of commit 2671e71e33543b17ef727994c8beddce0a6ce45e, I no longer see the crash (Ubuntu 12.04). However, it's still not working. I get about 500ms of moving video and then it freezes. Each refresh gets me another 500ms or so, but I can never "stream". I assume that's a different bug though.

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
