### ISSUE TITLE
Events all report continuous even when it is a motion event. 

### ISSUE THREAD

**Issue by baudneo** [ZoneMinder/zoneminder#3854]
My custom ml setup checks the cause of the event, ie. Motion|Continuous|Forced web|ONVIF and doesn't run if it isn't a motion or triggered event (skips continuous). ~~I don't know exactly which commit it was~~, but I compiled on march 2nd around 11AM MDT.

Not a big issue, just thought I would mention it.

Edit: Pretty sure it was this commit: https://github.com/ZoneMinder/zoneminder/commit/904f0627693538661c385933590af7315315dd81
The last commit I compiled before that was February 18th @ 10:52 AM MST: https://github.com/ZoneMinder/zoneminder/commit/def378fe12b58ca121669f13e438b268d2b2d64a

**Comment by connortechnology** [comment]
I completely refactored the state machine logic...  and I've certainly seen similar reports, but thought it resolved in late Feb.  Need debug logs around the start of an event that should have been cause=Motion.  Also there are new EVENT_CLOSE_MODE settings that may be the issue.  It may be incorrectly falling bcak to IDLE instead of Alarm.

**Comment by baudneo** [comment]
Kk, I'll get some debug logs this evening. Thanks!

**Comment by Simpler1** [comment]
I'm still seeing this problem also.  About 80% of my events show a cause of Continuous even though I only ever record on motion.

**Comment by baudneo** [comment]
Log file is huge lol, I think the event starts somewhere around 18:21:22 ish. This monitor was a view only monitor, no recording or modect. I turned modect on to create an event and it came out as continuous, so the logging should hopefully show what's up.

[zmc_m15.log](https://github.com/ZoneMinder/zoneminder/files/14544521/zmc_m15.log)

**Comment by connortechnology** [comment]
Latest code may fix this. Please update and report.

**Comment by ppnacho69** [comment]
I'm at V1.37.55 updated yesterday and I'm also full of Continuous "Cause" events. 
![zoneminder](https://github.com/ZoneMinder/zoneminder/assets/61601589/5338ec26-d98a-46c2-9264-b8c0e562b6c1)

**Comment by connortechnology** [comment]
I believe 503b1ae97 fixes this.

**Comment by ppnacho69** [comment]
Runs nice now, only Motion events are recorded. But now when alarmed, the red border of the image doesn't appear, it keeps being white as on idle state. I'm running on V1.37.55) upgraded today.

**Comment by ppnacho69** [comment]
Solved, only event triggers are recorded now on V1.37.55. Thank you

**Comment by baudneo** [comment]
Fixed!
