### ISSUE TITLE
mpeg stream method not work: connection refused

### ISSUE THREAD

**Issue by vlad2005** [ZoneMinder/ZoneMinder#473]
I try to use mpeg stream method with zoneminder but failed with this error:
web_php 8591    ERR socket_sendto( /tmp/zm/zms-077598s.sock ) failed: Connection refused    /usr/share/zoneminder/includes/functions.php    2330

Step to reproduce:
1. chose for option WEB_H_STREAM_METHOD value mpeg
Specs: 
zoneminder                                1.27.0+1-trusty-SNAPSHOT2014070904           i386
OS:
Ubuntu 14.04
##

**Comment by connortechnology** [comment]
Can you please try 1.28 or even better current master dev branch?  I just fixed one crash in zms, and it may be yours.

**Comment by connortechnology** [comment]
I am currently updating my ppa, which I see you are using.     Please make sure that you get snapshot 2015012901 at least

**Comment by vlad2005** [comment]
Hi!
Currently i use 1.28 and with this option still not work. I have two types of cams: local and libvlc. Local cam show an static image and libvlc don't show anything. If need, later i will test more and got some logs to post here.

**Comment by kylejohnson** [comment]
@vlad2005 Assuming your 'Bandwidth' option is set to 'High',
 * `WEB_H_STREAM_METHOD` is set to `mpeg`?
 * What is `MPEG_LIVE_FORMAT` set to?
 * What is `MPEG_REPLAY_FORMAT` set to?
 * What is `WEB_USE_OBJECT_TAGS` set to?

**Comment by vlad2005** [comment]
WEB_H_STREAM_METHOD -> mpeg
MPEG_LIVE_FORMAT -> swf
MPEG_REPLAY_FORMAT -> swf
WEB_USE_OBJECT_TAGS -> true (option check)
Now follows the strangeness. I have an capture card with two broadcom chipsets an 16 cams (i know that is bad :) ). All have same settings, the most important:
Captures Per Frame -> 2
Cam on /dev/video0(0) and /dev/video1(0) work properly using mpeg stream. In the remaining cams image is frozen.
Both IP cam wich work using libvlc still not work.

**Comment by kylejohnson** [comment]
That `ERR socket_sendto` error itself is usually not the real issue.

Try this:
 1. Change both `MPEG_LIVE_FORMAT` and `MPEG_REPLAY_FORMAT` to `webm`.
 2. Open a new monitor stream to view it live
 3. Inspect the HTML code, and find the `<embed>` or `<object>` tag.  
 4. Grab the URL inside of the `src` attribute, e.g.: `vlc 'http://zmdev01/cgi-bin/zms?mode=mpeg&monitor=25&scale=100&bitrate=10000000&maxfps=30&format=webm&connkey=484161&rand=1422377232'`
 5. Open that URL inside of VLC
 6. If the stream doesn't work, try changing from `webm` to `ogg`.
 7. Tell me what happens

**Comment by vlad2005** [comment]
Google chrome (latest version 40.0.2214.94) work with both options webm and ogg.
Firefox 35.0.1 require plugin for both options. I don't know why because is supposing that firefox support both video streaming. I will investigate more.
All test are made on Xubuntu 14.04. Also i test firefox on windows XP but I met the same issue, about missing plugins.
Also i want to mention that switching between views is significantly slower when using mpeg streaming mode.

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
