### ISSUE TITLE
Logging after RTSP warning causes crash (segfault)

### ISSUE THREAD

**Issue by bill-mcgonigle** [ZoneMinder/zoneminder#903]
I'm connecting to a network camera via RTSP (plays OK in mplayer) and it works for a few seconds before zm processes begin to segfault.

I'm not positive but it looks like the crash is in the sql logging part.  This is an example from the logfile:

```
Jun 24 02:20:26 zoneminder zmc_m1[1312]: WAR [Unexpected format RTSP interleaved data, resyncing by 48 bytes]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: WAR [48: 36 c0 a7 36 13 0a c1 91 bf e8 d5 c3 74 c7 06 66 ad a5 f6 64 25 44 fb 4f 9d c6 fa f5 4b 4f a5 0e 91 62 4f a2 9e 38 4e 81 ed d5 ea e7 27 d6 4e 7e]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: WAR [Unexpected format RTSP interleaved data, resyncing by 253 bytes]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: WAR [253: d7 b0 ee ce 7c e2 3c c8 0b a7 d2 18 46 30 77 00 41 b6 77 0f c5 4e f2 89 90 92 c6 9a dc 11 40 4f 8c 46 5a 2b 7d ea a4 c0 b3 0a b5 df 3d 2c b5 e2 c6 7b 49 bf a2 ea 26 62 d9 6a 0c ca 62 70 78 20 c2 e3 b3 2b 8e 78 34 42 6b 2c e8 03 d2 96 95 9e ac 8e b0 a5 11 a3 eb a4 60 32 30 de af 42 2a e6 af 6d e9 35 8e de 5b af 1c 9f aa 6d 0c 50 56 c2 a3 60 7f 22 0b 0f c8 9d 93 f6 ce 09 57 4b 42 03 8e 3b 04 23 1c 43 4d 28 0a de ac 61 6e 3b d5 b2 15 5f 22 f0 8f bb 58 0f 74 08 ef 67 9b 18 4c f7 c4 e5 26 45 c9 49 49 5e 73 3d ab 9a d2 f0 66 f9 d9 d3 07 e5 47 ac 96 c9 5b e9 ea f6 c9 3b 8f 63 b4 db bd 2c 8d ca 1c 4c 21 db 26 ca 16 f3 3f 52 53 25 c4 40 6e f0 f1 88 21 ec c6 c7 af a7 d6 36 76 e2 1a 3d 68 a8 93 2c 4a 80 3a 71 6c c6 41 b7 00 be 77 90 da 8f e3 b5 4e 04 13 01 b5]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Unexpected channel selector 170 in RTSP interleaved data]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: WAR [Unexpected format RTSP interleaved data, resyncing by 607 bytes]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: FAT [Can't insert log entry: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''607: 29 b5 bf 60 a8 77 41 03 3a 99 6e 2e 99 ee dd ec 04 b0 dd 6d 23 d9 21 40 07' at line 1]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Got signal 11 (Segmentation fault), crashing]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Signal address is 0x18, from 0x7f2734ef8c00]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 0: /usr/bin/zmc(_Z14zm_die_handleriP9siginfo_tPv+0x72) [0x7f27360e4332]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 1: /lib64/libpthread.so.0(+0xf130) [0x7f2734efe130]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 2: /lib64/libpthread.so.0(pthread_mutex_lock+0) [0x7f2734ef8c00]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 3: /lib64/libtspi.so.1(host_table_final+0x14) [0x7f272f4cbbb4]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 4: /lib64/ld-linux-x86-64.so.2(+0xfb5a) [0x7f2735e3eb5a]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 5: /lib64/libc.so.6(+0x38e49) [0x7f2731dbce49]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 6: /lib64/libc.so.6(+0x38e95) [0x7f2731dbce95]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 7: /usr/bin/zmc(_ZN6Logger8logPrintEbPKciiS1_z+0x42a) [0x7f273607bf9a]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 8: /usr/bin/zmc(_ZN6Logger8logPrintEbPKciiS1_z+0x962) [0x7f273607c4d2]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 9: /usr/bin/zmc(_ZN10RtspThread3runEv+0x4483) [0x7f27360cd3d3]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 10: /usr/bin/zmc(_ZN6Thread11mThreadFuncEPv+0xb2) [0x7f27360edb02]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 11: /lib64/libpthread.so.0(+0x7df5) [0x7f2734ef6df5]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: ERR [Backtrace 12: /lib64/libc.so.6(clone+0x6d) [0x7f2731e7a1ad]]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: INF [Backtrace complete, please execute the following command for more information]
Jun 24 02:20:26 zoneminder zmc_m1[1312]: INF [addr2line -e /usr/bin/zmc 0x7f27360e4332 0x7f2734efe130 0x7f2734ef8c00 0x7f272f4cbbb4 0x7f2735e3eb5a 0x7f2731dbce49 0x7f2731dbce95 0x7f273607bf9a 0x7f273607c4d2 0x7f27360cd3d3 0x7f27360edb02 0x7f2734ef6df5 0x7f2731e7a1ad]
Jun 24 02:20:26 zoneminder zmdc[1243]: ERR ['zmc -m 1' exited abnormally, exit status 11]
```

I rebuilt the zmrepo packages locally to get debug symbols, but if addr2line can use separate debuginfo, gnu hides that well (anybody know if/how?).  I ran zmc under gdb to get some info (local ip's anonymized):

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe5bf6700 (LWP 2160)]
0x00007ffff6ea4c00 in pthread_mutex_lock () from /lib64/libpthread.so.0
(gdb) thread apply all bt full

Thread 3 (Thread 0x7fffe5bf6700 (LWP 2160)):
#0  0x00007ffff6ea4c00 in pthread_mutex_lock () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007ffff1477bb4 in host_table_final () from /lib64/libtspi.so.1
No symbol table info available.
#2  0x00007ffff7deab5a in _dl_fini () from /lib64/ld-linux-x86-64.so.2
No symbol table info available.
#3  0x00007ffff3d68e49 in __run_exit_handlers () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff3d68e95 in exit () from /lib64/libc.so.6
No symbol table info available.
#5  0x000055555557cf9a in Logger::logPrint (this=<optimized out>, hex=hex@entry=false, file=file@entry=0x5555556744a0 "/root/rpmbuild/BUILD/ZoneMinder-1.28.1/src/zm_logger.cpp", 
    line=line@entry=588, level=level@entry=-3, fstring=fstring@entry=0x555555674394 "Can't insert log entry: %s") at /usr/src/debug/ZoneMinder-1.28.1/src/zm_logger.cpp:603
        classString = "FAT"
        timePtr = <optimized out>
        tid = <optimized out>
        logPtr = <optimized out>
        syslogStart = <optimized out>
        logString = "06/24/15 02:28:52.428829 zmc_m1[2160].FAT-/root/rpmbuild/BUILD/ZoneMinder-1.28.1/src/zm_logger.cpp/588 [Can't insert log entry: You have an error in your SQL syntax; check the manual that corresponds "...
        timeString = "06/24/15 02:28:52.428829", '\000' <repeats 39 times>
        argPtr = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffe5bf20f8, reg_save_area = 0x7fffe5bf2000}}
        timeVal = {tv_sec = 1435127332, tv_usec = 428829}
        syslogEnd = <optimized out>
#6  0x000055555557d4d2 in Logger::logPrint (this=<optimized out>, hex=hex@entry=true, file=file@entry=0x555555679698 "/root/rpmbuild/BUILD/ZoneMinder-1.28.1/src/zm_rtsp.cpp", 
    line=line@entry=752, level=level@entry=-1, fstring=fstring@entry=0x555555678b4d "%p (%d)") at /usr/src/debug/ZoneMinder-1.28.1/src/zm_logger.cpp:588
        sql = "insert into Logs ( TimeKey, Component, Pid, Level, Code, Message, File, Line ) values ( 1435127332.428243, 'zmc_m1', 2160, -1, 'WAR', '347: 91 9c 1a 95 85 6a f9 d2 45 9d ab 4b 18 54 fd 86 1a f4 5f b0 "...
        escapedString = 0x7fffe5bf2130 "347: 91 9c 1a 95 85 6a f9 d2 45 9d ab 4b 18 54 fd 86 1a f4 5f b0 9f 5a 5a 93 86 fb 97 31 aa 64 bd b5 43 30 8e 5d f1 e9 98 2c 1a 56 ee 35 ef 7e cf 81 9e e1 84 49 76 c0 77 88 37 de 97 29 f9 64 8c c1 41 "...
        classString = "WAR"
        timePtr = <optimized out>
        tid = <optimized out>
        logPtr = <optimized out>
        syslogStart = <optimized out>
        logString = "06/24/15 02:28:52.428243 zmc_m1[2160].WAR-/root/rpmbuild/BUILD/ZoneMinder-1.28.1/src/zm_rtsp.cpp/752 [347: 91 9c 1a 95 85 6a f9 d2 45 9d ab 4b 18 54 fd 86 1a f4 5f b0 9f 5a 5a 93 86 fb 97 31 aa 64 bd "...
        timeString = "06/24/15 02:28:52.428243\000+\277\345\377\177\000\000\177K\277\345\377\177\000\000\200+\277\345\377\177\000\000\177K\277\345\377\177\000\000\000\000\000\000\000\000\000"
        argPtr = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffe5bf4f50, reg_save_area = 0x7fffe5bf4e50}}
        timeVal = {tv_sec = 1435127332, tv_usec = 428243}
        syslogEnd = <optimized out>
#7  0x00005555555ce3d3 in RtspThread::run (this=0x55555ad08bb0) at /usr/src/debug/ZoneMinder-1.28.1/src/zm_rtsp.cpp:752
        discardBytes = 347
        readable = std::vector of length 1, capacity 1 = {0x55555ad08c78}
        tempBuffer = "\253\006\356{*\361T+<P\226ʺ\203\345\275\331M\247\300_\246\335\214\246\024:\363\330Z\311P\314(r\270l\217\244o\246:\033\217I#\232\a\365\005\r\221\027ל\267Ғn+\366&\002\333q\217\253Cu\271\034\231\236\to\006\340\276\375+*\206\311`\314%Iۼ!\030s+Z\327\002\361C$!0\311\067\234\245\260)\v#\\\301\361\330\020\034\253\255wD3\323\376\350\022\256\220>x\332\314e\266\360\000\257\334sI]\002\324\fB\227\034x\267\062\222\031qJ\325\002̚g\321+\nsi]\250\276!\233\301\223\227\214\322\320\033A\205\212<$QW\336\270\314K\023\316\331+\325:x%\272\327J`\360\264\207\036.\204'\372Q\t"...
        nBytes = <optimized out>
        rtpCtrlThread = {<Thread> = {_vptr.Thread = 0x55555589e770 <vtable for RtpCtrlThread+16>, mThread = 140737284297817, mThreadMutex = {mMutex = {__data = {__lock = 0, __count = 0, 
                  __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, mThreadCondition = {
              mMutex = @0x7fffe5bf58d0, mCondition = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, 
                  __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}, mPid = -1, mStarted = false, mRunning = false}, mRtspThread = @0x55555ad08bb0, 
          mRtpSource = @0x7fffe000c380, mPort = 0, mStop = false}
        select = {mReaders = std::set with 1 elements = {[0] = 0x55555ad08c78}, mWriters = std::set with 0 elements, mReadable = std::vector of length 1, capacity 1 = {0x55555ad08c78}, 
          mWriteable = std::vector of length 0, capacity 0, mHasTimeout = true, mTimeout = {tv_sec = 2, tv_usec = 500000}, mMaxFd = 13}
        buffer = {mStorage = 0x7fffe0024570 "$", mAllocation = 65536, mSize = 32079, 
          mHead = 0x7fffe0025574 "\221\234\032\225\205j\371\322E\235\253K\030T\375\206\032\364_\260\237ZZ\223\206\373\227\061\252d\275\265C0\216]\361\351\230,\032V\356\065\357~ρ\236\341\204Iv\300w\210\067ޗ)\371d\214\301A\240\346\215z\r/*.Zu\364Hв\247\337\307\020\245l\267\061\371\273\302\001\304b\003~`\267g)\215ny\270\222\375\335\332\025R\223\240\036\305\301\316\022\305Vx\313.\205#؏\302\067\210\370S`3+\364\374\203-\364K\005ERp\205", 
          mTail = 0x7fffe002d2c3 "t\227b\272\315\\\377\250\271R\037\001\031s\360\253\313\\\267\330\070O\237\217\252\071-\235\230<`l8\031Z~N)\351\023\252g\374yr\016Z\244\356iC\330r\323\020\3---Type <return> to continue, or q <return> to quit--- 
67\251\302\225\214 \356\360Q\333M\255Q\312<]\360!k\257]\251\302h\021\301\256T7\t^q@\374\257\257\025E\261ܵ^ܵ\267buyz\301\063}\230)\361*\351\276\302n\216\236\f.A\002l\363v\220\016\247\332뤸J\n@\244\313\017C<\267vö\254\027\300\006cg\354\373\030W}4Ywc\253\fW/،\034\203\036\006S\301\366\366\037R}\373Z\216\003\004\205\262+\337XX?W\374\375\t\266\241 \rj\vE\355D"...}
        keepaliveResponse = "RTSP/1.0 200 OK\r\n"
        source = <optimized out>
        rtpDataThread = {<Thread> = {_vptr.Thread = 0x55555589f1b0 <vtable for RtpDataThread+16>, mThread = 140737284145176, mThreadMutex = {mMutex = {__data = {__lock = 0, __count = 0, 
                  __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, mThreadCondition = {
              mMutex = @0x7fffe5bf5840, mCondition = {__data = {__lock = 0, __futex = 0, __total_seq = 0, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, 
                  __broadcast_seq = 0}, __size = '\000' <repeats 47 times>, __align = 0}}, mPid = -1, mStarted = false, mRunning = false}, mRtspThread = @0x55555ad08bb0, 
          mRtpSource = @0x7fffe000c380, mStop = false}
        lastKeepalive = 1435127328
        keepaliveMessage = "OPTIONS rtsp://camera.example.com:554/mpeg4 RTSP/1.0\r\n"
        remotePorts = <optimized out>
        distribution = "unicast"
        ssrc = <optimized out>
        rtpInfo = "url=rtsp://10.1.1.15//track1;seq=18269;rtptime=1344285807"
        transport = "RTP/AVP/TCP;unicast;destination=10.1.1.14;source=10.1.1.15;interleaved=0-1", '\000' <repeats 176 times>
        method = "RTP/RTSP"
        timeout = 0
        remoteChannels = <optimized out>
        parts = std::vector of length 3, capacity 8 = {"url=rtsp://10.1.1.15//track1", "seq=18269", "rtptime=1344285807"}
        seq = <optimized out>
        rtpTime = <optimized out>
        streams = std::vector of length 1, capacity 1 = {"url=rtsp://10.1.1.15//track1;seq=18269;rtptime=1344285807"}
        endOfHeaders = "\r\n\r\n"
        rtpClock = <optimized out>
        trackUrl = "rtsp://camera.example.com:554/mpeg4/track1"
        codecId = AV_CODEC_ID_H264
        response = "RTSP/1.0 200 OK\r\nCSeq: 4\r\nDate: Wed, Jun 24 2015 06:28:49 GMT\r\nRange: npt=0.000-\r\nSession: 1C9EDE7E\r\nRTP-Info: url=rtsp://10.1.1.15//track1;seq=18269;rtptime=1344285807\r\n\r\n"
        authTried = <optimized out>
        publicLine = "OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, SET_PARAMETER", '\000' <repeats 193 times>
        session = "1C9EDE7E"
        message = "PLAY rtsp://camera.example.com:554/mpeg4 RTSP/1.0\r\nSession: 1C9EDE7E\r\nRange: npt=0.000-\r\n"
        localHost = "10.1.1.14"
        lines = std::vector of length 6, capacity 6 = {"RTSP/1.0 200 OK", "CSeq: 4", "Date: Wed, Jun 24 2015 06:28:49 GMT", "Range: npt=0.000-", "Session: 1C9EDE7E", 
          "RTP-Info: url=rtsp://10.1.1.15//track1;seq=18269;rtptime=1344285807"}
        sdp = "v=0\r\no=- 22526427 1 IN IP4 10.1.1.15\r\ns=RTSP/RTP stream from Network Video Server\r\ni=mpeg4\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2011.05.25\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-t"...
        controlUrl = "track1"
        localPorts = {1523617008, -440445360}
        sendKeepalive = false
        res = <optimized out>
        sdpStart = <optimized out>
#8  0x00005555555eeb02 in Thread::mThreadFunc (arg=0x55555ad08bb0) at /usr/src/debug/ZoneMinder-1.28.1/src/zm_thread.cpp:264
        run = 32767
        thisPtr = 0x55555ad08bb0
        status = 0x0
#9  0x00007ffff6ea2df5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00007ffff3e261ad in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7ffff7fb9900 (LWP 2154)):
#0  0x00007ffff3ded48d in nanosleep () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff3e1e014 in usleep () from /lib64/libc.so.6
No symbol table info available.
#2  0x0000555555572786 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/ZoneMinder-1.28.1/src/zmc.cpp:287
        sleep_time = <optimized out>
        min_delay = <optimized out>
        i = 0
        device = <optimized out>
        protocol = 0x555555673e65 ""
---Type <return> to continue, or q <return> to quit---
        port = <optimized out>
        log_id_string = "zmc_m1", '\000' <repeats 25 times>
        n_monitors = 1
        capture_delays = 0x55555ad08460
        result = 0
        path = <optimized out>
        monitor_id = <optimized out>
        next_delays = 0x55555ad232f0
        now = {tv_sec = 1435127332, tv_usec = 418925}
        modes = <optimized out>
        host = <optimized out>
        alarm_capture_delays = 0x55555ad232d0
        delta_time = {positive = true, delta = <optimized out>, sec = <optimized out>, fsec = <optimized out>, prec = <optimized out>}
        file = <optimized out>
        long_options = {{name = 0x5555556739a1 "device", has_arg = 1, flag = 0x0, val = 100}, {name = 0x5555556739a8 "protocol", has_arg = 1, flag = 0x0, val = 114}, {
            name = 0x555555677dd2 "host", has_arg = 1, flag = 0x0, val = 72}, {name = 0x5555556739b1 "port", has_arg = 1, flag = 0x0, val = 80}, {name = 0x555555674c5a "path", 
            has_arg = 1, flag = 0x0, val = 112}, {name = 0x5555556739b6 "file", has_arg = 1, flag = 0x0, val = 102}, {name = 0x5555556739bb "monitor", has_arg = 1, flag = 0x0, val = 109}, 
          {name = 0x5555556739c3 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        monitors = 0x55555ad01f80
        block_set = {__val = {2560, 0 <repeats 15 times>}}
```

When it crashes, mysql logs incomplete SQL statements (see middle one below).  I notice the size of the hex blob is pretty big, but on the mysql side it's a TEXT field, so that should be OK.  Maybe something is too small on the logging side?

```
                   52 Query     insert into Logs ( TimeKey, Component, Pid, Level, Code, Message, File, Line ) values ( 1435116860.218413, 'zmc_m1', 6046, -1, 'WAR', 'Unexpected format RTSP interleaved data, resyncing by 479 bytes', '/builddir/build/BUILD/ZoneMinder-1.28.1/src/zm_rtsp.cpp', 751 )
                   52 Query     insert into Logs ( TimeKey, Component, Pid, Level, Code, Message, File, Line ) values ( 1435116860.219006, 'zmc_m1', 6046, -1, 'WAR', '479: 5e cf 21 56 ee e5 30 e2 ea 12 11 ef 57 d5 13 b2 74 67 8f 94 06 0c 82 95 2c f5 83 2c fc c2 23 63 34 a6 ae 03 d0 1d 2c 5b 69 ee c2 8c b7 37 11 78 70 e5 8f 39 fe cb 26 0c d1 0e 92 72 c9 b8 c3 53 d7 fc 42 9e ad 40 aa 78 16 da 8b 7f 15 40 ab ba 96 cb 35 62 5b d9 48 1c 83 26 23 75 cf 22 19 d8 95 c5 a8 9d ac 54 4e e9 df 0c e2 84 b5 b9 a0 ed 3d a0 50 2a 31 28 b2 79 78 d1 a8 21 9c ec ad c4 ac 6e 90 d6 45 ab b0 10 6f 88 33 f0 a9 f0 bf 65 bb a9 ab 7c 5e 6b 8b 68 bd 4b 42 38 f1 22 3d ea 0d 8c e4 31 73 c4 5f 0e b5 74 76 3b 8f e3 d3 e2 33 1f 4c 92 54 01 40 74 78 c4 1f dc 3c 6a de 0e 54 40 0f 72 47 00 50 20 11 7c dc 79 a6 92 48 1e 57 63 06 85 6f fd fc 8a 5e 13 7d 55 2e f9 ee db 5d ed 3a b5 8d 34 60 c4 80 b5 ee 54 78 2a 19 61 ca fe ec ea fe 44 7c bf 46 d0 87 b8 fb 26 7e 8e 49 67 77 5f b1 82 b4 ac f3 98 ca 94 18 26 e6 00 a4 db ac 5f 60 73 0e db 01 c0 16 6f a0 0b 7b fd 41 7b c4 b8 5e 6a 4
                   48 Query     insert into Logs ( TimeKey, Component, Pid, Level, Code, Message, File, Line ) values ( '1435116860.24626', 'zmdc', '6015', '-2', 'ERR', '\'zmc -m 1\' exited abnormally, exit status 11', 'zmdc.pl', NULL )
```

I think there's a separate RTSP handling problem here too, but that'll be easier to debug with stable logging.
##

**Comment by connortechnology** [comment]
I wonder if this is a multi-threading concurrency issue, like more than one thread trying to access the db at once?

I've seen this, and in master we merged a patch to make db logging failures not fatal, but still there is something going on here.

**Comment by bill-mcgonigle** [comment]
just for grins, based on [stackoverflow] (http://stackoverflow.com/questions/1455190/how-to-access-mysql-from-multiple-threads-concurrently) I added this to zmc.cpp:

````
        if ( mysql_library_init(0, NULL, NULL) ) 
        {
                fprintf( stderr, "Could not initialize MySQL library\n" );
                exit( -1 );
        }
````

and it didn't fix it.  Total shot in the dark (I'm out of my element); just adding here for completeness.  A link from the top comment there has guidance on thread safety in the mysql client library.
